# Generated by Django 2.2.27 on 2026-03-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_id'),
        ('books', '0002_auto_20260306_0310'),
    ]

    operations = [
    ]
