# Generated by Django 2.2.27 on 2026-03-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_id'),
        ('books', '0004_merge_20260312_0913'),
    ]

    operations = [
    ]
