# Generated by Django 2.2.27 on 2026-03-12 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20260306_0315'),
        ('reviews', '0004_alter_favourite_id_alter_review_id'),
    ]

    operations = [
    ]
