# Generated by Django 2.2.27 on 2026-03-15 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_merge_20260312_0913'),
        ('reviews', '0005_alter_favourite_id_alter_review_id'),
    ]

    operations = [
    ]
